/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'Monaco', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Main color palette
        primary: {
          50: '#FEF7F7',
          100: '#FDF0F0',
          200: '#FAD7D7',
          300: '#F5C0C0',
          400: '#F0A3A3',
          500: '#EA8686',
          600: '#E3B2B3',
          700: '#DD6B6B',
          800: '#C75555',
          900: '#A84444',
          950: '#8B3939',
        },
        // Accent colors
        accent: {
          jade: {
            50: '#F0FBF7',
            100: '#E1F7ED',
            200: '#C3EDD8',
            300: '#9FE1C2',
            400: '#75D1A5',
            500: '#5CB198',
            600: '#4A9A7D',
            700: '#3C8366',
            800: '#2F6B52',
            900: '#265643',
            950: '#142B22',
          },
          amethyst: {
            50: '#FAF7FC',
            100: '#F5EEFA',
            200: '#E8DAF3',
            300: '#D6C2E8',
            400: '#C09FD8',
            500: '#A477B2',
            600: '#8E5A96',
            700: '#76477C',
            800: '#5E3A64',
            900: '#4A2F50',
            950: '#281829',
          },
          citrine: {
            50: '#FEFAF0',
            100: '#FCF5E1',
            200: '#F7EAC3',
            300: '#F1DA9E',
            400: '#EAC574',
            500: '#CDA849',
            600: '#B0903A',
            700: '#93782F',
            800: '#786124',
            900: '#604F1D',
            950: '#32280F',
          },
        },
        // Surface colors
        surface: {
          DEFAULT: '#14141C',
          50: '#FBF9F9',
          100: '#F5F3F3',
          200: '#E3E1E1',
          300: '#201D25',
          400: '#111118',
          500: '#14141C',
          600: '#191820',
          700: '#252128',
          800: '#2B252C',
          900: '#312A31',
          950: '#01011B',
        },
        // Text colors
        text: {
          DEFAULT: '#E3B2B3',
          muted: '#99797D',
          loud: '#FFFFFF',
          secondary: '#717A94',
        },
        // Semantic colors
        main: '#E3B2B3',
        'accent-jade': '#5CB198',
        'accent-amethyst': '#A477B2',
        'accent-citrine': '#CDA849',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'scale-in': 'scaleIn 0.5s ease-out',
        'slide-in-left': 'slideInLeft 0.6s ease-out',
        'slide-in-right': 'slideInRight 0.6s ease-out',
        'bounce-subtle': 'bounceSubtle 2s infinite',
        'pulse-slow': 'pulse 3s infinite',
        float: 'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-mesh': 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #fda085 100%)',
      },
      boxShadow: {
        soft: '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        medium: '0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        strong: '0 10px 40px -10px rgba(0, 0, 0, 0.15), 0 4px 25px -5px rgba(0, 0, 0, 0.1)',
        glow: '0 0 20px rgba(59, 130, 246, 0.15)',
        'glow-lg': '0 0 40px rgba(59, 130, 246, 0.2)',
      },
      backdropBlur: {
        xs: '2px',
      },
      spacing: {
        18: '4.5rem',
        88: '22rem',
        128: '32rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.75rem' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      maxWidth: {
        '8xl': '88rem',
        '9xl': '96rem',
      },
      zIndex: {
        60: '60',
        70: '70',
        80: '80',
        90: '90',
        100: '100',
      },
      typography: () => ({
        DEFAULT: {
          css: {
            color: 'rgb(var(--color-text-body))',
            maxWidth: 'none',
            a: {
              'text-decoration': 'none',
              color: 'rgb(var(--color-text-link))',
              'font-weight': '500',
              '&:hover': {
                color: 'rgb(var(--color-text-link-hover))',
              },
            },
            'h1, h2, h3, h4, h5': {
              color: 'rgb(var(--color-text-heading))',
              'font-weight': '600',
            },
            h1: {
              'font-size': '2.25rem',
              'line-height': '1.2',
              'margin-top': '2rem',
              'margin-bottom': '1rem',
            },
            h2: {
              'font-size': '1.875rem',
              'line-height': '1.3',
              'margin-top': '2rem',
              'margin-bottom': '1rem',
            },
            h3: {
              'font-size': '1.5rem',
              'line-height': '1.4',
              'margin-top': '1.5rem',
              'margin-bottom': '0.75rem',
            },
            p: {
              'margin-top': '1rem',
              'margin-bottom': '1rem',
              'line-height': '1.7',
            },
            code: {
              'background-color': 'rgb(var(--color-code-bg))',
              color: 'rgb(var(--color-code-text))',
              padding: '0.125rem 0.375rem',
              'border-radius': '0.25rem',
              'font-size': '0.875rem',
              'font-weight': '500',
              'font-family': "JetBrains Mono, Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
            },
            pre: {
              'background-color': 'rgb(var(--color-pre-bg))',
              color: 'rgb(var(--color-pre-text))',
              padding: '1rem',
              'border-radius': '0.5rem',
              'overflow-x': 'auto',
              'font-size': '0.875rem',
              'line-height': '1.5',
              'font-family': "JetBrains Mono, Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
            },
            'pre code': {
              'background-color': 'transparent',
              padding: '0',
              'font-size': 'inherit',
            },
            blockquote: {
              border: 'none',
              position: 'relative',
              'font-style': 'italic',
              color: 'rgb(var(--color-text-muted))',
              'padding-left': '1.5rem',
              margin: '1.5rem 0',
            },
            'blockquote::before': {
              content: '""',
              position: 'absolute',
              left: '0',
              top: '0',
              bottom: '0',
              width: '3px',
              'background-color': 'rgb(var(--color-accent))',
              'border-radius': '2px',
            },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography'), require('@tailwindcss/aspect-ratio')],
};
